
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:462 (find_file)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:500 (CMAKE_DETERMINE_COMPILER_ID_WRITE)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineCCompiler.cmake:122 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    mode: "file"
    variable: "src_in"
    description: "Path to a file."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "CMakeCCompilerId.c.in"
    candidate_directories:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/"
    found: "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeCCompilerId.c.in"
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe"
        - "C:\\VulkanSDK\\1.4.341.1\\Bin"
        - "C:\\Program Files\\Microsoft\\jdk-21.0.10.7-hotspot\\bin"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\Yarn\\bin\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Users\\millfi\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\"
        - "C:\\Users\\millfi\\AppData\\Local\\Programs\\Python\\Python312\\"
        - "C:\\Users\\millfi\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\millfi\\AppData\\Roaming\\local\\bin"
        - "C:\\Users\\millfi\\scoop\\apps\\vscode\\current\\bin"
        - "C:\\Users\\millfi\\scoop\\apps\\haskell\\current\\lib\\bin"
        - "C:\\Users\\millfi\\scoop\\shims"
        - "C:\\Users\\millfi\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\millfi\\AppData\\Local\\Yarn\\bin"
        - "C:\\Users\\millfi\\.dotnet\\tools"
        - "C:\\Users\\millfi\\AppData\\Local\\Programs\\Zed\\bin"
        - "C:\\Users\\millfi\\AppData\\Local\\Microsoft\\WinGet\\Links"
        - "C:\\Users\\millfi\\AppData\\Local\\Programs\\Antigravity\\bin"
        - "C:\\Users\\millfi\\CLIapps"
        - "C:\\Users\\millfi\\AppData\\Local\\Microsoft\\WinGet\\Packages\\libjxl.libjxl_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "C:\\Users\\millfi\\.lmstudio\\bin"
        - "C:\\Users\\millfi\\AppData\\Local\\Keybase\\"
        - "C:\\Users\\millfi\\.local\\bin"
        - "C:\\Users\\millfi\\AppData\\Roaming\\npm"
        - "C:\\Users\\millfi\\.dotnet\\tools"
        - "C:\\Users\\millfi\\AppData\\Local\\PowerToys\\DSCModules\\"
        - "C:\\Users\\millfi\\AppData\\Local\\Voidstar\\FilePilot"
